<a href="https://colab.research.google.com/github/PRAN20/Best-Regressor/blob/main/BestRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Header Files**

In [54]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as mt

**Importing DataSets**

In [55]:
dataset = ps.read_csv('Data.csv')
x = dataset.iloc[ :, :-1].values
y = dataset.iloc[ :, -1].values

**Spliting DataSet**

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [57]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


**Performing Multiple Regression**

In [58]:
mult_x = x
mult_y = y

In [59]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [60]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [61]:
from sklearn.metrics import r2_score
res_mult = r2_score(y_test, y_pred)

In [62]:
print(res_mult)

0.9325315554761302


In [63]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


**Performing Polynomial Regression**

In [64]:
poly_x = x
poly_y = y

In [65]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [66]:
y_pred = regressor.predict(poly_reg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


In [67]:
from sklearn.metrics import r2_score
res_poly = r2_score(y_test, y_pred)

**Performing Random Forest Regression**

In [68]:
ran_x = x
ran_y = y

In [69]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [70]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


In [71]:
from sklearn.metrics import r2_score
res_ran = r2_score(y_test, y_pred)

**Performing Decision Tree Regression**

In [72]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [73]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


In [74]:
from sklearn.metrics import r2_score
res_tree  = r2_score(y_test, y_pred)

**Printing Results from All the Regression**

In [75]:
print('ACCURACY FROM MULTIPLE REGRESSION IS', res_mult)
print('ACCURACY FROM POLYNOMIAL REGRESSION IS', res_poly)
print('ACCURACY FROM RANDOM FOREST REGRESSION IS', res_ran)
print('ACCURACY FROM DECISION TREE REGRESSION IS', res_tree)

ACCURACY FROM MULTIPLE REGRESSION IS 0.9325315554761302
ACCURACY FROM POLYNOMIAL REGRESSION IS 0.9458192606428238
ACCURACY FROM RANDOM FOREST REGRESSION IS 0.9615908334363876
ACCURACY FROM DECISION TREE REGRESSION IS 0.922905874177941


**Checking Which Model is Best for the Given DataSet**

In [76]:
list = [res_mult, res_poly, res_ran, res_tree]

In [77]:
ans_reg = max(list)

In [78]:
if ans_reg == res_mult:
  print('Multiple Regression Has The Highest Accuracy')
if ans_reg == res_poly:
  print('Polynomial Regression Has The Highest Accuracy')
  flag = 1
if ans_reg == res_ran:
  print('Random Forest Regression Has The Highest Accuracy')
  flag = 2
if ans_reg == res_tree:
  print('Decision Tree Has The Highest Accuracy')
  flag = 3

Random Forest Regression Has The Highest Accuracy
